### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Vants/stampsreplacer#1]
Hi Vants,
I'm glad you did it in Python. It is my diploma work. I tried your project according to the instructions. 
And it does not work for me! Help me, Please!

**Comment by Vants** [comment]
Hello!

Please explain what seems to be the problem?  Does the program throws some exception in the middle of the process?

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/47080706/53075856-c44b3700-3520-11e9-8764-c751d24c5e60.JPG)
![2](https://user-images.githubusercontent.com/47080706/53075857-c4e3cd80-3520-11e9-8da7-27a606afd939.JPG)
Folders appear after compilation
![3](https://user-images.githubusercontent.com/47080706/53075978-18eeb200-3521-11e9-9172-328ddff64f99.JPG)
Result Not Received
![4](https://user-images.githubusercontent.com/47080706/53076492-5b64be80-3522-11e9-8d46-e13313ecb932.JPG)
I think I made a mistake. Thanks for your help!

**Comment by Vants** [comment]
Hello!

Sorry that I haven't answered your question. It has been busy week.

You compiled Python code to Cython but didn't start process. It seems that it is missing from quide/ readme.

For starting program/ processing you need to run _Main.py_.

Like so:
`python Main.py`
This starts from zeroth step and ends final. Runs all steps.

You can also add steps where to start (first parameter) and where to end (end parameter). Example:
`python Main.py 0 5`
This is also equal to previous command.

When we need to run only one step, then both parameters need to be equal. Example:
`python Main.py 0 0`

Also you can show step where to start. It starts from this step and ends with final step. Example:
`python Main.py 0`
This is also equal to first and second command.

What each step do:
0 - load SNAP files and data to Python and calculate some additional that is needed for next steps.
1 - Load SNAP files that where made for StaMPS to Python/ Numpy format.
2 - Estimate phase noise
3 - Select persistent scatterers
4 - Filter/ weed out persistent scatterers
5 - Phase correction

Please note that you can't start from first step when you haven't started zeroth step and so on. All steps depend from previous steps.

When this helps you I'll add this to readme.

**Comment by ghost** [comment]
Thank you. I will try this way.

**Comment by Vants** [comment]
Did it worked? Were you able to run program?

**Comment by ghost** [comment]
Thanks for asking! I will write to you in detail now. What mistakes I've made.

**Comment by ghost** [comment]
**OS:** Windows 10
**Python version**: 3.6.3
Made a virtual environment with name virtenv1 and installed libraries
![1](https://user-images.githubusercontent.com/47080706/56095194-77725400-5f04-11e9-80bc-67ffd596209f.JPG)
**Next, change the parameters**
![3](https://user-images.githubusercontent.com/47080706/56095347-eef4b300-5f05-11e9-8d79-367e75478b70.JPG)
![4](https://user-images.githubusercontent.com/47080706/56095348-f2883a00-5f05-11e9-9e1d-dbb541a96f6f.JPG)
**And compiled the project and got** 
![2](https://user-images.githubusercontent.com/47080706/56095366-311df480-5f06-11e9-9815-1905285e216b.JPG)
Thank you for helping and for consultation!

**Comment by ghost** [comment]
I get this error: ImportError: cannot import name ProductIO 
snappy 2.5.2  is already installed.

**Comment by ghost** [comment]
> Did it worked? Were you able to run program?

Hello!

### I tried on Windows 10 and very good 

### Compiled project in this way: 
_python_ cython_setup.py build_ext --inplace

### Successfully

### And For starting program I started process with this way: 
_python_ Main.py 0 5

### And I got these files
![1](https://user-images.githubusercontent.com/47080706/58224710-f602b280-7d48-11e9-8e20-6184f68c7759.jpg)

### Tell me please! Where to see the results?

### More question
### When I try to run test classes
### I get such errors
![2](https://user-images.githubusercontent.com/47080706/58224990-26971c00-7d4a-11e9-8172-327dabea3627.jpg)

**Comment by Vants** [comment]
Hello! Sorry for the late response.

> > Did it worked? Were you able to run program?
> 
> Hello!
> 
> ### I tried on Windows 10 and very good
> ### Compiled project in this way:
> _python_ cython_setup.py build_ext --inplace
> 
> ### Successfully
> ### And For starting program I started process with this way:
> _python_ Main.py 0 5
> 
> ### And I got these files
> ![1](https://user-images.githubusercontent.com/47080706/58224710-f602b280-7d48-11e9-8e20-6184f68c7759.jpg)
> 
> ### Tell me please! Where to see the results?

This means that the run was successful. But these arent complete result. Because my work didn't completely rewrite/ ported Stamps. There are some steps missing from the end (like phase unwrap).  It seems that this is also missing from the readme. The steps from the end are being rewritten/ ported to Python/ Numpy in TTÜ/ TalTec university.

Those files are savepoints for program. When you have complited first step with same data you can resume from there. You can open those using https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.savez.html and then it may be possible to make similar savefile and port results to Stamps and then continue work there. But this seems like too much hassle and little.

> ### More question
> ### When I try to run test classes
> ### I get such errors
> ![2](https://user-images.githubusercontent.com/47080706/58224990-26971c00-7d4a-11e9-8172-327dabea3627.jpg)

I need to look from my settings file. It seems like some config paramter isn't not shown.

**Comment by ghost** [comment]
Hello! 
Thank you for answering :)

After a successful run, appeared a folder "log" and Inside the folder is a file called debug.log
![1](https://user-images.githubusercontent.com/47080706/58749160-709ba280-84ac-11e9-9372-e5eaeec7e2c6.jpg)

I thought the results in this file

**Comment by ghost** [comment]
Sorry, Vants!

How did you do the performance tests for the work done? I mean how to compare the results with Matlab.
Please tell me more about this!
I really need this.

**Comment by Vants** [comment]
Is used log rows ("Start" and "End" delta)  for measuring time in Python/ Cython and in Matlab tic/ toc (https://se.mathworks.com/help/matlab/ref/tic.html?s_tid=doc_ta).

Matlab was faster in almost any test, about three or ten times faster. It is possible to make Python even faster using multithreading or parallelism workflow. Then I think Python can be even faster.

**Comment by ghost** [comment]
Thanks for the quick response.

**Comment by Yunik155** [comment]
> Is used log rows ("Start" and "End" delta) for measuring time in Python/ Cython and in Matlab tic/ toc (https://se.mathworks.com/help/matlab/ref/tic.html?s_tid=doc_ta).
> 
> Matlab was faster in almost any test, about three or ten times faster. It is possible to make Python even faster using multithreading or parallelism workflow. Then I think Python can be even faster.

**Comment by ghost** [comment]
> Hello!
> Thank you for answering :)
> 
> After a successful run, appeared a folder "log" and Inside the folder is a file called debug.log
> ![1](https://user-images.githubusercontent.com/47080706/58749160-709ba280-84ac-11e9-9372-e5eaeec7e2c6.jpg)
> 
> I thought the results in this file

**These are not results then?**

**Comment by ghost** [comment]
> Those files are savepoints for program. When you have complited first step with same data you can resume from there. You can open those using https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.savez.html and then it may be possible to make similar savefile and port results to Stamps and then continue work there. But this seems like too much hassle and little.

### As I understand it, the results of python can only be seen with the help of this?

**Comment by Vants** [comment]
Yes, but this isn't very correct place where to look. This is meant for debugging. When you have very big array then it only logs begin and end. When you open .npz file there are there results.

**Comment by ghost** [comment]
https://github.com/Vants/stampsreplacer/issues/1#issuecomment-497950541
Very excellent, Vants!
Thank you for respect again)
